spring:
  datasource:
    ###可读数据源
    select:
      jdbc-url: jdbc:mysql://127.0.0.1:8066/mycat_testdb
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: 123456
    ####可写数据源
    update:
      jdbc-url: jdbc:mysql://127.0.0.1:8066/mycat_testdb
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
